"""initial tables

Revision ID: 29bbdbd8d410
Revises: 
Create Date: 2026-05-30 18:29:36.865864

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '29bbdbd8d410'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pincodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('post_office_name', sa.String(length=200), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pincode_trgm', 'pincodes', ['post_office_name'], unique=False, postgresql_using='gin', postgresql_ops={'post_office_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_pincodes_pincode'), 'pincodes', ['pincode'], unique=False)
    op.create_table('ration_shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ard_number', sa.String(length=50), nullable=False),
    sa.Column('dealer_name', sa.String(length=300), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('tso_code', sa.String(length=50), nullable=False),
    sa.Column('location_raw_string', sa.Text(), nullable=True),
    sa.Column('pincode_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pincode_id'], ['pincodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ard_number')
    )
    op.create_table('shop_stock_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('last_checked_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_stock_delivered', sa.Boolean(), nullable=True),
    sa.Column('month_cycle', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['ration_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shop_month', 'shop_stock_status', ['shop_id', 'month_cycle'], unique=True)
    op.create_table('stock_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_status_id', sa.Integer(), nullable=False),
    sa.Column('commodity_name', sa.String(length=200), nullable=False),
    sa.Column('allocated_quantity', sa.Float(), nullable=True),
    sa.Column('received_quantity', sa.Float(), nullable=True),
    sa.Column('arrival_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_status_id'], ['shop_stock_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_items')
    op.drop_index('idx_shop_month', table_name='shop_stock_status')
    op.drop_table('shop_stock_status')
    op.drop_table('ration_shops')
    op.drop_index(op.f('ix_pincodes_pincode'), table_name='pincodes')
    op.drop_index('idx_pincode_trgm', table_name='pincodes', postgresql_using='gin', postgresql_ops={'post_office_name': 'gin_trgm_ops'})
    op.drop_table('pincodes')
    # ### end Alembic commands ###
